name: pytopkapi-master
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::bzip2=1.0.6=1
- conda-forge::ca-certificates=2017.4.17=0
- conda-forge::certifi=2017.4.17=py36_0
- conda-forge::curl=7.52.1=0
- conda-forge::decorator=4.0.11=py36_0
- conda-forge::expat=2.1.0=2
- conda-forge::freexl=1.0.2=1
- conda-forge::gdal=2.2.0=np112py36_0
- conda-forge::geos=3.5.1=1
- conda-forge::giflib=5.1.4=0
- conda-forge::h5py=2.7.0=np112py36_0
- conda-forge::hdf4=4.2.12=0
- conda-forge::hdf5=1.8.17=10
- conda-forge::icu=58.1=1
- conda-forge::jpeg=9b=0
- conda-forge::json-c=0.12=0
- conda-forge::kealib=1.4.7=1
- conda-forge::krb5=1.14.2=0
- conda-forge::libdap4=3.18.3=2
- conda-forge::libiconv=1.14=4
- conda-forge::libnetcdf=4.4.1.1=4
- conda-forge::libpng=1.6.28=0
- conda-forge::libpq=9.5.4=4
- conda-forge::libspatialite=4.3.0a=14
- conda-forge::libtiff=4.0.6=7
- conda-forge::libxml2=2.9.4=4
- conda-forge::ncurses=5.9=10
- conda-forge::networkx=1.11=py36_0
- conda-forge::nose=1.3.7=py36_2
- conda-forge::numexpr=2.6.2=np112py36_0
- conda-forge::numpy=1.12.1=py36_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openjpeg=2.1.2=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pip=9.0.1=py36_0
- conda-forge::proj4=4.9.3=3
- conda-forge::pytables=3.4.2=np112py36_0
- conda-forge::python=3.6.1=3
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.19.0=np112py36_blas_openblas_200
- conda-forge::setuptools=33.1.1=py36_0
- conda-forge::six=1.10.0=py36_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::wheel=0.29.0=py36_0
- conda-forge::xerces-c=3.1.4=3
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
- libgfortran=3.0.0=1
- lzo=2.06=0
- mkl=2017.0.1=0
- util-linux=2.21=0
- pip:
  - pytopkapi-0.3.0.dev==1ed357e
  - tables==3.4.2

